extends: wikimedia/server
parserOptions:
  ecmaVersion: 10
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: off
  space-in-parens: [error, never]
  computed-property-spacing: [error, never]
plugins:
  - json