
#
# Topic config file for eventbus produce service.
# This file specifies which schemas are allowed to be produced
# to topics.  Learn more at https://wikitech.wikimedia.org/wiki/EventBus
#
# Note: This topic config used to be in WMF's operations/puppet repo.
# It may find a better home one day, but keeping it in this repository
# allows it to be used by services outside of WMF production.
#

mediawiki.page-delete:
  schema_name: mediawiki/page/delete

mediawiki.page-move:
  schema_name: mediawiki/page/move

mediawiki.page-undelete:
  schema_name: mediawiki/page/undelete

mediawiki.page-properties-change:
  schema_name: mediawiki/page/properties-change

mediawiki.revision-visibility-change:
  schema_name: mediawiki/revision/visibility-change

mediawiki.revision-create:
  schema_name: mediawiki/revision/create

mediawiki.user-blocks-change:
  schema_name: mediawiki/user/blocks-change

resource_change:
  schema_name: resource_change
