
#
# Topic config file for eventbus produce service.
# This file specifies which schemas are allowed to be produced
# to topics.  Learn more at https://wikitech.wikimedia.org/wiki/EventBus
#
# Note: This topic config used to be in WMF's operations/puppet repo.
# It may find a better home one day, but keeping it in this repository
# allows it to be used by services outside of WMF production.
#

mediawiki.page-create:
  # A page create is just a special case of revision create,
  # so we can reuse the same schema.
  schema_name: mediawiki/revision/create

mediawiki.page-delete:
  schema_name: mediawiki/page/delete

mediawiki.page-move:
  schema_name: mediawiki/page/move

mediawiki.page-undelete:
  schema_name: mediawiki/page/undelete

mediawiki.page-properties-change:
  schema_name: mediawiki/page/properties-change

mediawiki.page-restrictions-change:
  schema_name: mediawiki/page/restrictions-change

mediawiki.revision-visibility-change:
  schema_name: mediawiki/revision/visibility-change

mediawiki.revision-create:
  schema_name: mediawiki/revision/create

mediawiki.revision-score:
  schema_name: mediawiki/revision/score

mediawiki.user-blocks-change:
  schema_name: mediawiki/user/blocks-change

mediawiki.recentchange:
  schema_name: mediawiki/recentchange

resource_change:
  schema_name: resource_change

## Continuation topics for backlinks processing in change propagation service
change-prop.backlinks.continue:
  schema_name: change-prop/continue

## Continuation topics for transcludes processing in change propagation service
change-prop.transcludes.continue:
  schema_name: change-prop/continue

## General error topic for change propagation
change-prop.error:
  schema_name: error

## Transclusion rerender topics for change propagation service
change-prop.transcludes.resource-change:
  schema_name: resource_change

# Change propagation retry queues
/^change-prop\.retry\..+/:
  schema_name: change-prop/retry

## MediaWiki Job topics
/^mediawiki\.job\..+/:
  schema_name: mediawiki/job
